version: '3'

volumes:
  pg_data:
  static:
  media:
  ./config/nginx/conf.d:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: amalshakov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: amalshakov/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: nginx:1.22.1
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media
      - ./config/nginx/conf.d:/etc/nginx/conf.d
